### ISSUE TITLE
Autosave prior to compilation

### ISSUE THREAD

**Issue by lampo808** [mathiasfrohlich/vscode-LaTeXCompile#10]
It would be nice to have an option to automatically save the edited document before the compilation occurs (I forget that many times and wonder why I see non changes in the pdf...).

Thanks for all the good work!

**Comment by mathiasfrohlich** [comment]
In the version 0.5.0 the work space is now saved.

But there is also an autosave option you can set in "user settings".
https://code.visualstudio.com/Docs/customization/userandworkspace

"files.autoSave": "afterDelay",
"files.autoSaveDelay": 1,

**Comment by lampo808** [comment]
Great, I didn't notice that!
