### ISSUE TITLE
Add /d into the constructed command to execute 

### ISSUE THREAD

**Issue by affans** [mathiasfrohlich/vscode-LaTeXCompile#13]
I have VS code installed on `C:\`. So the exec command runs it from the C drive. However, the file/folder I am working in is on an external drive, assigned letter `D:\`. 

The problem with window's `cd` function is that it does not switch drives unless the `/d` switch is present. Can we add this in (or is there a way I can modify my personal extension?)? 

note: It won't break existing behaviour .

**Comment by mathiasfrohlich** [comment]
@affans  This have now been implemented. This is included in the newest version 0.6.0.
