### ISSUE TITLE
Fake compile tex file

### ISSUE THREAD

**Issue by wwzoon** [mathiasfrohlich/vscode-LaTeXCompile#14]
Hello, with new update of El capitan at version 10.11.5 the extension compile the file after the command, but it doesnt do something. With another program or terminal i can compile it, but i prefer this extension :)

**Comment by RoadToDream** [comment]
I encountered the same problem. 
the extension works great in some files but not all.

**Comment by pierredewilde** [comment]
Same issue (MacOSX 10.11.5). Nothing happen except 'Launching [PDF]' message in status bar.

**Comment by mathiasfrohlich** [comment]
What are you user settings?
Do you have a Latex installed on you system ? (miktex for Windows, mactex for OSX)

Want to help this problem, but I dont have an OSX(newly MacOS) machine any more and cannot test this. 

Does the .pdf compile ? 

Does the program open the pdf ?

Have you checked the "latexCompile.compiler": "pdflatex" Settings option ?
This should be set to how your latex distributions compiles. Not all can compile with pdflatex.

Have you tried typing open {documentName}.pdf in the terminal to see if it can open ?

**Comment by RoadToDream** [comment]
I am using Windows, I have installed texlive and the pdf file is not compiled. 
I think the problem might be caused by the latest release 1.2.1.

**Comment by mathiasfrohlich** [comment]
@RoadToDream From what I can tell in the texlive documentation, page 17:
https://www.tug.org/texlive/doc/texlive-en/texlive-en.pdf
It should be possible to type "pdflatex sample2e.tex" in cmd to compile any .tex file to pdf.
Can you confirm this ? 
I am on windows 10 latest vscode and able to replicate this.

**Comment by RoadToDream** [comment]
@mathiasfrohlich I am not sure and I will have a try.

**Comment by pierredewilde** [comment]
Hi Mathias,

Thanks for your support.

LaTeX has been correctly installed from https://tug.org/mactex/ (MacTeX-2016) :

```
$ tex -version
TeX 3.14159265 (TeX Live 2015)
...

$ pdflatex -version
pdfTeX 3.14159265-2.6-1.40.16 (TeX Live 2015)
...

$ pdflatex sample2e.tex
This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015) (preloaded format=pdflatex)
...
Output written on sample2e.pdf (3 pages, 136717 bytes).
Transcript written on sample2e.log.

$ open sample2e.pdf
=> successfully open sample2e.pdf file in Preview.
```

Please note that there is a known issue with MacOSX El Capitan (10.11.x) : 
LaTeX tools are now located in `/Library/TeX/texbin` instead of `/usr/texbin`.
https://tug.org/mactex/elcapitan.html 

```
$ which pdflatex
/Library/TeX/texbin/pdflatex
```

Here are the VS Code User/setting.json :

```
    // Latex Compile Configuration
    "latexCompile.openAfterCompile": true,
    "latexCompile.openLogAfterError": true,
    "latexCompile.compiler": "pdflatex"
```

I naïvely try to set `pdflatex` location without success:

`"latexCompile.compiler": "/Library/TeX/texbin/pdflatex"`

**Comment by RoadToDream** [comment]
@mathiasfrohlich yep the tex file can correctly be compiled.
![cmd_2016-06-23_20-40-38](https://cloud.githubusercontent.com/assets/8088354/16303405/0ff29898-3983-11e6-83ce-fbbc29a78de8.png)

**Comment by mathiasfrohlich** [comment]
@pierredewilde Thanks for the thorough description.
As you describe if the commands work in the terminal. There is not much more I can do.

"latexCompile.compiler": "/Library/TeX/texbin/pdflatex", setting this will not work. 
It will replace the "pdflatex" with it and generate this command : 
"/Library/TeX/texbin/pdflatex sample2e.tex”
Don’t think this will work, you are welcome to try it out in the terminal.
If you have another idea of how to point to the correct compiler path and fix it, please submit at merge request. 

@RoadToDream Do you have the latest version of the extension ? 
In the latest you can use paths that contain " "(space). this was not possible in the previous version.
You can check this, or maybe move the .tex file into another folder so the path does not contain “spaces”. Just note that it seems like your user have spaces.

**Comment by RoadToDream** [comment]
@mathiasfrohlich thanks a lot! perfectly fixed. doesn't figure it out in the documentation.

**Comment by mathiasfrohlich** [comment]
@pierredewilde I have now added this to the documentation. 

"Please note that there is a known issue with MacOSX El Capitan (10.11.x) : 
LaTeX tools are now located in /Library/TeX/texbin instead of /usr/texbin.
https://tug.org/mactex/elcapitan.html"

To let other know of this problem.

@RoadToDream You are welcome. Good that it is now working for you.

**Comment by pierredewilde** [comment]
`cd /d` is not supported on MacOSX. Drive (eg C:) is a Windows-only concept.

```
var command = 'cd /d' + quote(path) + ' && ' + vscode.workspace.getConfiguration('latexCompile').compiler + ' ' + quote(fileNameAndType);
```

and

```
exec('cd /d' + quote(path) + ' && type NUL > ' + quote(fileName) + ".vscodeLog");
```

will fail on Mac and Linux.

```
var command = 'cd ' + quote(path) + ' && ' + vscode.workspace.getConfiguration('latexCompile').compiler + ' ' + quote(fileNameAndType);
```

and

```
exec('cd ' + quote(path) + ' && type NUL > ' + quote(fileName) + ".vscodeLog");
```

should work on both Mac and Linux but may fail on Windows if not the same drive.

**Comment by mathiasfrohlich** [comment]
Fixing this right now with :

var changeDirectory = "cd "

if(process.platform == "win32")
      changeDirectory = "cd /d";

**Comment by mathiasfrohlich** [comment]
It is now Live
Thanks for the help

**Comment by pierredewilde** [comment]
Yep, it now works perfectly on MacOSX. Thanks for your prompt support.

**Comment by mathiasfrohlich** [comment]
You are welcome. Good that it is now working.
Thanks for helping me test this small extension.
