### ISSUE TITLE
pdf doesn't open after compiling

### ISSUE THREAD

**Issue by belggianny** [mathiasfrohlich/vscode-LaTeXCompile#2]
I edited my settings file to open the pdf file after compiling. 
When building is does say launching [pdf] in the bottom left corner but it doesn't actually open. Automatically opening the error log doesn't work either.

**Comment by mathiasfrohlich** [comment]
1. What system are you on ? 
2. What are you user settings?
3. Do you have a Latex installed on you system ? (miktex for Windows, mactex for OSX)

By default the setting are set to open .pdf and open .vscodeLog.
You may in your settings set this to false, if you so desire.
- If you don't want them to open, put this in you user setting.json
  "latexCompile.openAfterCompile": false,
  "latexCompile.openLogAfterError": false,
- If you want them to open, do nothing or put 
  "latexCompile.openAfterCompile": true,
  "latexCompile.openLogAfterError": true,

**Comment by belggianny** [comment]
I'm on windows 8
my user settings contains only this:
// Place your settings in this file to overwrite the default settings
{
    //Latex Compile Configuration
  "latexCompile.openAfterCompile": true,
  "latexCompile.openLogAfterError": true,

"properties": {
    "latexCompile.openAfterCompile": {
        "type": "boolean",
        "default": true,
        "description": "Opens PDF after Latex Compile" 
    },
    "latexCompile.openLogAfterError": {
        "type": "boolean",
        "default": true,
        "description": "Opens .vscodeLog if failed to Compile" 
    }
}  
}

**Comment by mathiasfrohlich** [comment]
Need to be clear on that you have a latex program installed ?

Im am sorry for the confusion.
You settings are not suppose to contain more than the first part.
You can copy paste the text below and replace everything in your settings with it :

// Place your settings in this file to overwrite the default settings
{
//Latex Compile Configuration
"latexCompile.openAfterCompile": true,
"latexCompile.openLogAfterError": true
}

**Comment by belggianny** [comment]
I have TeX Live installed. 
I should have mentioned that compiling works, the file just doesn't open automatically after compiling. 
btw, before switching to visual studio code I used sublimetext (and atom) with a similar plugin which worked, both compiling and automatically opening the file.

Copy-pasting those settings changed nothing.
I also tried changing my standard pdf reader, that didn't change anything either. 
Could it be that the path to the pdf reader needs to be specified somewhere?

**Comment by mathiasfrohlich** [comment]
Good to hear that it does compile.

It have nothing to do with the standard pdf reader. After compiled it simply calls the command line open path/fileName.pdf. This is a way of opening the file from cmd. Like double clicking the file.

Cannot explain why the pdf does not open, you are welcome to Fork the repository and commit a fix, if you can find one.

Your settings should not have changed anything but are now correct. That can rule out some potential problems.

**Comment by belggianny** [comment]
okay, thanks for your quick response anyway.

**Comment by mathiasfrohlich** [comment]
You are welcome
