### ISSUE TITLE
Error Cannot read property '1' of null

### ISSUE THREAD

**Issue by Ghostish** [mathiasfrohlich/vscode-LaTeXCompile#20]
Hello,  
I am using VSCODE 1.6.0 on Windows 10.
I intalled LaTexCompile 0.6.1 via the VSCODE extension market . 
but when I tried to complie I got an error :  
`Error Cannot read property '1' of null`

I tried to reinstall this extension but it was still not working. 

Any suggestion for me to solve this?

Thanks!

**Comment by jf908** [comment]
One of the requirements is to have a Latex distribution such as Miktex for Windows. I got this error before realising that it was a requirement.
