### ISSUE TITLE
Not working, and no error messages...

### ISSUE THREAD

**Issue by christianknu** [mathiasfrohlich/vscode-LaTeXCompile#3]
Hi Mathias

I have downloaded and installed your plugin.
But when I run it, nothing happens - I don't even get an error message.

I have installed the extension, restarted VS code.
Then I open a .tex file, and find the command in the "Command palette", I click the command and nothing happens.

System information:
OS: OSX 10.11.3
LaTex Distribution: MacTex

Do you have a suggestion to what could be wrong?

**Comment by mathiasfrohlich** [comment]
Hello

Thanks for using the extension.

It has possibly something to do with the 0.10.8 (January 2016) update, that have changed some of the way extensions use the internal vscode api.

I have submitted at new version of the extension and is now able to create pdf's myself.
Will you try updating through the ext update command in vscode and give it at shot.

Thanks for bringing this to my attention.

**Comment by christianknu** [comment]
Unfortunately it still does not work for me...
When I run the command, it says "Launching [pdf] DATETIME" and still nothing happens, where can I find the log?

**Comment by mathiasfrohlich** [comment]
Sorry that this did not solve the problem.

I have released a new version that might fix it. 
Can't really say for sure since it works on mine.

Sorry to ask you again, but can you update and and try again ?
If this does not work, try cloning the git repo and open the folder in vscode followed by pressing f5.
Then run the extension from Extension development host. 
This will give you a debug console of what is happening.

**Comment by Kenya-West** [comment]
Same here, it just says "Launching [pdf] DATETIME" and nothing happens. Where does it save pdf files by default?

UPD: More details:
• Visual Studio Code: the latest (0.10.8)
• Plug-in version: latest
• Windows 10: latest

**Comment by mathiasfrohlich** [comment]
@christianknu Did it solve you problem ?

@Kenya-West It compile and save the pdf, at the same location as the .tex file.
Do you have a Latex distribution on you system? (miktex for Windows, mactex for OSX)

**Comment by christianknu** [comment]
Hi Mathias
No unfortunately it didn't, I haven't tried cloning the repo and debug, I could try that.

**Comment by Kenya-West** [comment]
@mathiasfrohlich no I don't have any. And I haven't spotted pdf file in same folder.

**Comment by mathiasfrohlich** [comment]
@christianknu This will make you able to debug anything and change the code. 
If you are able to find a bug or fix it, please submit at merge request, from that i will review the code and publish it.

@Kenya-West I will need to have a latex distribution installed. This is also stated in the requirements.
https://github.com/mathiasfrohlich/vscode-LaTeXCompile#requirements

**Comment by christianknu** [comment]
I found that the path was the problem, I had a folder called "Git Repositories", which I then renamed to "Git-Repositories" and now it is working :smile:

**Comment by mathiasfrohlich** [comment]
@christianknu I see, i am glad you got the problem solved, i will include a description of this in the README.md, so others may avoid this problem.
