### ISSUE TITLE
Specify main file

### ISSUE THREAD

**Issue by GerjanOnline** [mathiasfrohlich/vscode-LaTeXCompile#4]
I have a large tex project with multiple files and 1 main file that includes everything.

Simplified structure

<pre>
/front
    title.tex
/content
    chapter1.tex
    chapter2.tex
/back
    bib.tex
main.tex % <= includes front, content, back
</pre>

Is it possible that this extensions always compiles `main.tex`, even when I am editing in another file? Maybe via a config file or something, or convention, or extra compile option..

Thanks!

**Comment by saul** [comment]
Using `latexmk -pdf` and specifying `% !TEX root = path_to_main_file.tex` in your non-root tex files would fix this.

**Comment by caffeinatedangel** [comment]
Just curious, how would you envision setting the main file to work?
The easiest thing to do might be have a command (LaTeX: Set Main Document?), but that sounds like it might be a little un-intuitive perhaps.

**Comment by GerjanOnline** [comment]
Currently I am using https://github.com/SublimeText/LaTeXTools and before that http://www.latexing.com/

They both have an option to specify the main file with a setting:
- http://docs.latexing.com/stable/tutorials/set-up-a-project.html#second-method-sublime-text-project-file
- https://github.com/SublimeText/LaTeXTools#compiling-latex-files

I know you can solve it with `TEX root` but I don't like it because I have a very modular thesis (more than 50 tex files, using the `subfiles` package)

However, i'm not sure how VS Code handles custom setting/project files, I know it has a `.vscode` folder for some projects to maintain tasks etc

**Comment by mathiasfrohlich** [comment]
@GerjanOnline There have now been implemented a feature that adresses this. This is included in the newest version 0.5.0.
