### ISSUE TITLE
Configurable latex command

### ISSUE THREAD

**Issue by Jadaw1n** [mathiasfrohlich/vscode-LaTeXCompile#6]
The Latex command seems to be hard coded. Can you add a setting to specify an alternative Latex program? I'd like to use XeTex :)

**Comment by mathiasfrohlich** [comment]
Hello

Thanks for using the extension.

I am unfamiliar with XeTex, are you not able to use pfdlatex to compile from command line ? 
If not how wound you then do it ?

**Comment by Jadaw1n** [comment]
Thanks for making the extension!

No, I use some packages which are only compatible with XeTex.
I just use the command xelatex in place of pdflatex.

**Comment by caffeinatedangel** [comment]
Should this be closed as of 0.4.0?

**Comment by mathiasfrohlich** [comment]
@Jadaw1n There have been implemented, a feature that allow yo to specify what compiler you want to us. This is can be done in user settings. Se README.md for more instructions.

@caffinatedangel Yes this was the idea. But simply ran out of time yesterday.

**Comment by Jadaw1n** [comment]
Nice, thank you both!
