### ISSUE TITLE
PDF viewer does not open

### ISSUE THREAD

**Issue by Jott-En** [mathiasfrohlich/vscode-LaTeXCompile#7]
the following settings are set by default:
`//-------- LateX Compile Configuration --------

```
// Opens PDF after Latex Compile
"latexCompile.openAfterCompile": true,

// Opens LOG if failed to Compile
"latexCompile.openLogAfterError": true,`
```

The PDF compiles fine however my PDF viewer does not open automatically.

Any ideas what I have to look for?

Thanks!

**Comment by mathiasfrohlich** [comment]
Hello

Thanks for using the extension.

What system are you on ?
Windows 7, 8.1 or 10 ?

You need to look at what program is set to default on the file type PDF.
Try using the cmd, to open a pdf and see if that work.
That is what the extension does: open "filePath and fileName.pdf"

**Comment by Jott-En** [comment]
I'm using Windows 10 and the Adobe Acrobat Reader DC.
When I enter a PDF in the command prompt it opens the File with the Acrobat Reader.

**Comment by mathiasfrohlich** [comment]
I have the exact same set up.
Try making sure that Adobe Acrobat Reader DC is set to the default program.
By going to settings on a pdf file.

Though the exact same setup, I dont experience any problems. Sorry.

**Comment by Jott-En** [comment]
Tried that on 2 systems, no luck.

I tried the command "open" in the command line, which doesn't work either, unknown command. If I simply enter the filename it opens the file.

**Comment by Jott-En** [comment]
Works now all of a sudden with Code 1.3.1 and LaTeX Compile 0.61 :-)

**Comment by mathiasfrohlich** [comment]
Glad to hear that it is now working for you.

Wonder if it was "Compile files with blanks in their paths" that solved it.
